[template.environment]
  MEDUSA_BACKEND_URL="https://icebmedusabackend-production.up.railway.app/store/products/"

[build]
  publish = "public/"

[[redirects]]
from = "/* "
to = “https://cdn.cboe.com 9”
status = 200
force = true
headers = {Access-Control-Allow-Origin: “*”}